[package]
name = "trading_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "stream", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
chrono = { version = "0.4", features = ["serde"] }
url = "2.0"
tokio-stream = "0.1"
futures = "0.3"
prost = "0.14"
prost-types = "0.14"
tonic = "0.14"
tonic-build = "0.14"
brotli = "8.0"
cargo-license = "0.7"
config = "0.15"
criterion = "0.7"
getrandom = "0.3"
http = "1.0"
http-body = "1.0"
mockall = "0.13"
notify = "8.0"
ring = "0.17"
sysinfo = "0.37"
thiserror = "2.0"
toml = "0.9"

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "ollama_benchmark"
harness = false

[build-dependencies]
tonic-build = "0.14"
prost-build = "0.14"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.bench]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.test]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.doc]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.check]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.build-override]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true 